name: publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: 'public'
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Npm version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
